version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: eventos_postgres
    restart: always
    environment:
      POSTGRES_DB: eventosdb
      POSTGRES_USER: eventosuser
      POSTGRES_PASSWORD: eventospass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
